// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOFmJVZbfaFJ7NyKx4d4QEG0G8xc7KkU',
    appId: '1:665176182069:web:270397c194d19cdebb507c',
    messagingSenderId: '665176182069',
    projectId: 'atrevet-parquea2',
    authDomain: 'atrevet-parquea2.firebaseapp.com',
    storageBucket: 'atrevet-parquea2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDwyJZQnUEjZP7SoY4YcqrnF0x1gVEXcI',
    appId: '1:665176182069:android:fc8ad9e3e8ba7592bb507c',
    messagingSenderId: '665176182069',
    projectId: 'atrevet-parquea2',
    storageBucket: 'atrevet-parquea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmBFKG3PT4hy4AfcMTCkXFu-Kf-jLuSL4',
    appId: '1:665176182069:ios:f1b47ceb5a340f50bb507c',
    messagingSenderId: '665176182069',
    projectId: 'atrevet-parquea2',
    storageBucket: 'atrevet-parquea2.appspot.com',
    iosBundleId: 'com.example.parquea2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmBFKG3PT4hy4AfcMTCkXFu-Kf-jLuSL4',
    appId: '1:665176182069:ios:67081e921d63c15bbb507c',
    messagingSenderId: '665176182069',
    projectId: 'atrevet-parquea2',
    storageBucket: 'atrevet-parquea2.appspot.com',
    iosBundleId: 'com.example.parquea2.RunnerTests',
  );
}
